// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyMsg.proto

package com.lee.vshare.service.netty.protobuf;

public final class NettyMessage {
  private NettyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NettyMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NettyMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 msgId = 1;</code>
     */
    int getMsgId();

    /**
     * <code>string userId = 2;</code>
     */
    String getUserId();
    /**
     * <code>string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>int32 token = 3;</code>
     */
    int getToken();

    /**
     * <code>int32 msgType = 4;</code>
     */
    int getMsgType();

    /**
     * <code>string msgContent = 5;</code>
     */
    String getMsgContent();
    /**
     * <code>string msgContent = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgContentBytes();
  }
  /**
   * Protobuf type {@code NettyMsg}
   */
  public  static final class NettyMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NettyMsg)
      NettyMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NettyMsg.newBuilder() to construct.
    private NettyMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NettyMsg() {
      userId_ = "";
      msgContent_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NettyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 24: {

              token_ = input.readInt32();
              break;
            }
            case 32: {

              msgType_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              msgContent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyMessage.internal_static_NettyMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyMessage.internal_static_NettyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyMsg.class, Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>int32 msgId = 1;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <code>string userId = 2;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private int token_;
    /**
     * <code>int32 token = 3;</code>
     */
    public int getToken() {
      return token_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <code>int32 msgType = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 5;
    private volatile Object msgContent_;
    /**
     * <code>string msgContent = 5;</code>
     */
    public String getMsgContent() {
      Object ref = msgContent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      }
    }
    /**
     * <code>string msgContent = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      Object ref = msgContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeInt32(1, msgId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (token_ != 0) {
        output.writeInt32(3, token_);
      }
      if (msgType_ != 0) {
        output.writeInt32(4, msgType_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgContent_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (token_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, token_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, msgType_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NettyMsg)) {
        return super.equals(obj);
      }
      NettyMsg other = (NettyMsg) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (getToken()
          != other.getToken()) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getMsgContent()
          .equals(other.getMsgContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NettyMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NettyMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NettyMsg)
        NettyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyMessage.internal_static_NettyMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyMessage.internal_static_NettyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMsg.class, Builder.class);
      }

      // Construct using com.lee.vshare.service.netty.protobuf.NettyMessage.NettyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0;

        userId_ = "";

        token_ = 0;

        msgType_ = 0;

        msgContent_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyMessage.internal_static_NettyMsg_descriptor;
      }

      @Override
      public NettyMsg getDefaultInstanceForType() {
        return NettyMsg.getDefaultInstance();
      }

      @Override
      public NettyMsg build() {
        NettyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NettyMsg buildPartial() {
        NettyMsg result = new NettyMsg(this);
        result.msgId_ = msgId_;
        result.userId_ = userId_;
        result.token_ = token_;
        result.msgType_ = msgType_;
        result.msgContent_ = msgContent_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMsg) {
          return mergeFrom((NettyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyMsg other) {
        if (other == NettyMsg.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getToken() != 0) {
          setToken(other.getToken());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getMsgContent().isEmpty()) {
          msgContent_ = other.msgContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgId_ ;
      /**
       * <code>int32 msgId = 1;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msgId = 1;</code>
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgId = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>string userId = 2;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int token_ ;
      /**
       * <code>int32 token = 3;</code>
       */
      public int getToken() {
        return token_;
      }
      /**
       * <code>int32 token = 3;</code>
       */
      public Builder setToken(int value) {
        
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 token = 3;</code>
       */
      public Builder clearToken() {
        
        token_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msgType = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msgType = 4;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgType = 4;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object msgContent_ = "";
      /**
       * <code>string msgContent = 5;</code>
       */
      public String getMsgContent() {
        Object ref = msgContent_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgContent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgContent = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgContentBytes() {
        Object ref = msgContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgContent = 5;</code>
       */
      public Builder setMsgContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgContent = 5;</code>
       */
      public Builder clearMsgContent() {
        
        msgContent_ = getDefaultInstance().getMsgContent();
        onChanged();
        return this;
      }
      /**
       * <code>string msgContent = 5;</code>
       */
      public Builder setMsgContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgContent_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NettyMsg)
    }

    // @@protoc_insertion_point(class_scope:NettyMsg)
    private static final NettyMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyMsg();
    }

    public static NettyMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NettyMsg>
        PARSER = new com.google.protobuf.AbstractParser<NettyMsg>() {
      @Override
      public NettyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NettyMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NettyMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NettyMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public NettyMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NettyMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NettyMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016NettyMsg.proto\"]\n\010NettyMsg\022\r\n\005msgId\030\001 " +
      "\001(\005\022\016\n\006userId\030\002 \001(\t\022\r\n\005token\030\003 \001(\005\022\017\n\007ms" +
      "gType\030\004 \001(\005\022\022\n\nmsgContent\030\005 \001(\tB5\n%com.l" +
      "ee.vshare.service.netty.protobufB\014NettyM" +
      "essageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NettyMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NettyMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NettyMsg_descriptor,
        new String[] { "MsgId", "UserId", "Token", "MsgType", "MsgContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
